### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by misobadev** [Ulysseassoo/ChatMore#4]
Is there a SQL file to migrate to supabase?

**Comment by Ulysseassoo** [comment]
There's none, would you need one ?

**Comment by misobadev** [comment]
It would be very helpful to know what structure the DB should have when I try this app that looks very interesting

**Comment by Ulysseassoo** [comment]
I'll be posting it this weekend for sure

**Comment by Ulysseassoo** [comment]
![Supbase Schema](https://user-images.githubusercontent.com/73486687/190270303-4c0ec208-fba8-4a44-ac2e-172a9b754a18.png)
Here is the schema of the DB that i went with
